version: '3.4'

services:
  accounts.web:
    image: accountsweb
    build:
      context: .
      dockerfile: ../Accounts.Web/Dockerfile

  accounts.api:
    image: accountsapi
    build:
      context: .
      dockerfile: src/Accounts.API/Dockerfile

